sudo: true
language: bash
services:
  - docker

env:
  global:
    - secure: "tCZ2WG0pOE4yOWxlCwG0rdma7CrSHjqoeQgEq2BiHdnMmBpb0Qp4RCOCEuF36v3/cQBXJE18OkaulRlQkaVwv9KVn39k0OkOLJmphpBRjISYoAjTwmcNw+3O1733nMR3rcq7OJ2l7c/Sfk5mwHDbk0lbX1N7DYgCpdgYmAtCGhnvhfHqHmihXGpD4a0lek5g0ekb0WeY7/JWCED0fvXUzTYC0vQUNHcbc3lbE3d2copyagNTAqOXdZPXTcdN1Of2nphyImMkZA7yDsKjCMGdCfw+nuSixTZAFwxYvZCjUN0TRxfHXLLF0uQ1AQVm1oZaA9DuDrsLXhruiLwtAZ+/I7m0MFSZZrcR/ltpbxyHlZKQoB865qt9AGBW5iziZ8nfkWML+fI7LkC5xrHoxxeGf9pketYW6OY9ypiR4oo+wEbSQkpH0UITYcKA1dUJRwMzDwlBOcC3hJ5HgkPO9yt3GJfUe+wuh0IoxeR3O6u9FQw/WYFh5GiiMsrwPCqsSHJrD12mnNiNMM5FUQEHtLipEje6fbXjCQ67lKCQK7yBqgQhYZ1MLK4p8whF2lu+Wk/ljYpLat29dxH20z4mdoGE4sPuPdDcTV9ShQpVaeNkFn3jCvUCaAizVTHfe7NM3nz0+gnjT4Xa1w2zLgJZEzkl+mXnBXoBf8JVdb+/MjOt7Go="

script: "./deploy/build.sh"
