language: ruby
rvm:
  - 2.4.1
cache: bundler

env:
  global:
    - JEKYLL_ENV: production
    - secure: "gTQGvOuVpn1qbtLxCivs+EGpbrgeNGe3Zg4buf53pLWfUsN5fZ7PleegCb9Io2Gq9/64pINNZ7bNiALvWXO54SKVe+LYpp4QtBp519hg8Ezfp4EbYr8hG+HZsQk0Nk5SnmKImLK3zAkZChd8c+9/7W7J+nO+FrC59e8UrHrlzbAokYhULK8crgywDZjupG/A50Y2S0RZuZQrwtiOb09IQiTwBLVEFtRXDywQiiBpAQo8NIL/aODo1cKvC6ZQ2bT/XmorXDXQ4pNKreA9gz+FSRFj8kgwdPyvcShcVuOBmt2yvkPRP+dBWxcP9MHliTqrqvOFbY9pOGWcI+/IWxB1w6nvEdFuPY8UDjy0b4p2tvV/s7/+psA5bj0omrT9Zwu1ZdyufO2LoWGi2uWW6DX+5mU50+UMlACSKUNfSSQ5cGdrq0IExbK0Cb4mZTrIP8mIN+lbfpv+vui78bNA3KF9LdDzfpOQmeqv2Ro2dFCkO42u6NdIdlYIUOnKAZms0GYvCfr7483+lcqtNA8V4bwErk7fIc5OxcxoBK9TF1NvHBlKD1CjAiSmHo74xMsNntcNMx9fmbjv6nnKSIhShgT8Yvkat+vMUpmpasZl4qMonWVDMDoc9eSIvfnqfg/edVO8QYPeJ3ODLK8hdL/r8FuA24kqFyggPg0f6cn0pD5Q72A="

install: bundler install
script: jekyll build

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "jac-peakwinter-net"
  region: "ca-central-1"
  skip_cleanup: true
  local_dir: _site
  on:
    branch: master
