sudo: true
language: bash
services:
- docker

env:
  global:
    - project: peakwinternet
    - server: node01.srv.coderouge.co
    - deploy_to: /var/data/peakwinter/site
    - secure: CsqPIiQcb8ebysZ+vrAsC+6Su2KGWrf/RtB/O8RTNe/hkOyK7zmpAhdBa44gT3B6dSIvNp+K+nyviiTWCkjI95jnMeUyUYNP0/yoKwJDbysK8beQn/HxMNhZNrnIgvdBJmJ+Ep/wIR2XlibCwUTAdLdf+jtAiFLIlcJokY8TP7ylddYYrWynXUsbLHroPg/sfmQst/SJLX/VzT8IUOEVeW9Eo2AZlzYlOxyOcfBihsBWZTIroVUhDMDh5Ly0ff1FO8NNDHukfE14RYPnu0KgCJw4EpgvfAGYZLhCXCy81zbZF4mhoWCl97O6G1u18/QaxcDVyuDSnavSJ2XpipPIOTxj9fVeb2e/EMm//g+AA/jfXSNq7pLkOC0/+yUamKhQMbNjB3fHhIWHO+47fcIEVRpVMcSq3sj6iJwImCNQnpzbd2vViLSOLThUpdowksTue2a5DD3Q/oPHwbNQeWIg9k/7wcQQNDkVSRfXAlJ1IO7I68LdX+TYjnS92O9PDGkcPmZr+b66Dl0IRapnxcjj2Xqar4co/LyiolADP7BopKJS+k8SlOIdHhJkbZzrbSLMl/A4QHLrSAOI0U94UjdLriVCoqR19r+/gTogAG3FJKhruYeoap/2fEqDv++GmDDFlDPR0zlYzqm7QI+TqAi0k7M4h/w0xaL5+oAcFhCwY5g=

script: "./deploy/build.sh"

deploy:
  provider: script
  script: "./deploy/deploy.sh"
  on:
    branch: master
