language: ruby
sudo: false
rvm:
- 2.2
env:
  global:
  - domain: peakwinter.net
  - site_path: "/var/www/site"
  - secure: VqOTNbymEHvkw19y11oEA4t+GTV2pjTABEKA2+INiAOgwNpQn2EAi6aY4mLcn+tVQFVKCEq2G8VwF8hBDU8SM79SYwi5BEUA62aMTCJ3bw9+IV82B8PX/1rxhA3it9+VR3J9yqBE9S0iCnBLCxOuj4AVre9+TfmC5oSnj6hzg1SfCZb/T3dFOquZoXZT3JoUyPg8t0J8VOFYFzXxebldO/W395jhy/qLyQr3uj3KbNY75IbrorKkx1l4V8WRWG+fRgNEj+QlZelCbnVsMwmZDyp72mKIcM4zKDE5GCS0Cb4Rj5va1AGdjgyLRqZY43h1vIfXdvzycbuMmZiiBxR+MhANEijoHzKS1D0ffgZsTF8O5JIX+WA/RmwjdYUV4t2LDfAVI5gHrm6DDA7iW3GTDwJ2O/1BmY1VQEpJPyV7bG82gftpllQDGF8Nv4idj3tdMGCJGdxsEYnTlfrC1N4e++zOKKKrFDRbt2lKE7X4M7MFWQyUs41qd0EHkzScn7Xi/MytqKXAb120yseOhsAkW4Rveg2bxTAxP2wjJSnkB+8aRuDyMlpJzsQV3e57NnFOH60CA6B3qE1aQllQTCedWAr1YLYav6rrJWmoW56ssMZz5M6mtt45iaZagzzCQFXO0GlOUWsKPyGmpzXCpg9bspYa7W8YzyMs01nMYeEUwzE=
script: bundle exec jekyll build
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy/deploy.sh"
  on:
    branch: master
