gems:
  - jekyll-seo-tag
  - jekyll-paginate

include: [.well-known]
exclude: [deploy, Gemfile, Gemfile.lock, README.md, LICENSE, vendor, Dockerfile, docker-compose.yml]

title: Jacob Cook
email: jacob@peakwinter.net
description: Personal website and blog
url: https://peakwinter.net
author:
  name: Jacob Cook
  twitter: peakwinter
  picture: /static/img/profile.jpg
logo: /static/img/apple-touch-icon.png

keybase: peakwinter
github: peakwinter
twitter:
  username: peakwinter
mastodon: peakwinter
lastfm: Midnight818
linkedin: peakwinter
instagram: peakwinter

social:
  name: Jacob Cook
  links:
    - https://twitter.com/peakwinter
    - https://mastodon.social/users/peakwinter
    - https://instagram.com/peakwinter
    - https://github.com/peakwinter
    - https://keybase.io/peakwinter
    - https://www.last.fm/user/Midngiht818
    - https://linkedin.com/in/peakwinter

defaults:
  - scope:
      path: ""
    values:
      image: /static/img/profile.jpg

google_site_verification: "-YXoyanxvJmQwWi-ed8nmVSm222RsGDII4-VtV6H2X0"

permalink: /blog/:title/
paginate: 5
port: 3000

kramdown:
  input: GFM
  syntax_highlighter: rouge
rdiscount:
  extensions: [smart]
