highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /blog/:title/
paginate: 5
gems: [jekyll-paginate, jekyll-tagging]
port: 3000
safe: true

url: https://peakwinter.net
baseurl: "/"
title: Jacob Cook
author: Jacob Cook
description: Personal website and blog
avatar: profile.jpg
email: jacob@peakwinter.net
keybase: peakwinter
github: peakwinter
twitter: peakwinter
mastodon: peakwinter
lastfm: Midnight818
linkedin: peakwinter
instagram: peakwinter

include: [.well-known]
exclude: [deploy, Gemfile, Gemfile.lock, README.md, LICENSE]
