version: '3'

services:
  web:
    image: peakwinter/peakwinter.net:latest
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:peakwinter.net,www.peakwinter.net"
        - "traefik.backend=peakwinternet"
        - "traefik.docker.network=public"

networks:
  public:
    external: true
