apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peakwinter-net
  labels:
    app: peakwinter-net
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: peakwinter-net
    spec:
      containers:
      - image: peakwinter/peakwinter.net:latest
        name: web
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: peakwinter-net
  labels:
    app: peakwinter-net
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: peakwinter-net
